export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_IS_ADMIN_FAILED = 'SET_IS_ADMIN_FAILED';
export const SET_IS_ADMIN = 'SET_IS_ADMIN';

export const UPDATE_ORDER_START = 'UPDATE_ORDER_START';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

export const ORDER_QUANTITY_CHANGED = 'ORDER_QUANTITY_CHANGED';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const FETCH_CART_ORDERS_START = 'FETCH_CART_ORDERS_START';
export const FETCH_CART_ORDERS_SUCCESS = 'FETCH_CART_ORDERS_SUCCESS';
export const FETCH_CART_ORDERS_FAIL = 'FETCH_CART_ORDERS_FAIL';

export const DELETE_CART_ORDER_START = 'DELETE_CART_ORDER_START';
export const DELETE_CART_ORDER_SUCCESS = 'DELETE_CART_ORDER_SUCCESS';
export const DELETE_CART_ORDER_FAIL = 'DELETE_CART_ORDER_FAIL';

export const ORDER_FROM_CART_START = 'ORDER_FROM_CART_START';
export const ORDER_FROM_CART_SUCCESS = 'ORDER_FROM_CART_SUCCESS';
export const ORDER_FROM_CART_FAIL = 'ORDER_FROM_CART_FAIL';
